import os
import sys
import subprocess
import re
from pathlib import Path
from rich import print


def check_virtual_environment():
    """Check if user is inside a virtual environment."""
    in_venv = (
        hasattr(sys, 'real_prefix') or
        (hasattr(sys, 'base_prefix') and sys.base_prefix != sys.prefix)
    )
    if not in_venv:
        print("[bold red]⚠ You are not inside a virtual environment![/bold red]")
        print("[yellow]Please create and activate a virtual environment first:[/yellow]")
        print()
        print("  [cyan]python -m venv env[/cyan]")
        print()
        print("  [cyan]# Windows:[/cyan]")
        print("  [cyan]env\\Scripts\\activate[/cyan]")
        print()
        print("  [cyan]# Mac/Linux:[/cyan]")
        print("  [cyan]source env/bin/activate[/cyan]")
        print()
        import typer
        raise typer.Exit(1)


def validate_name(name: str, label: str = "name"):
    """Validate that name is a valid Python identifier."""
    if not name.isidentifier():
        print(f"[red]Error: '{name}' is not a valid {label}. Use only letters, numbers, and underscores. Must not start with a number.[/red]")
        import typer
        raise typer.Exit(1)
    if name[0].isdigit():
        print(f"[red]Error: '{name}' must not start with a digit.[/red]")
        import typer
        raise typer.Exit(1)


def update_settings_file(settings_path: str, name: str):
    with open(settings_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Extract the original SECRET_KEY generated by Django
    match = re.search(r"SECRET_KEY\s*=\s*(['\"].*?['\"])", content)
    secret_key = match.group(1) if match else "'your-secret-key-here'"

    # 1. Add imports at the top
    content = content.replace(
        "from pathlib import Path",
        "from pathlib import Path\nfrom datetime import timedelta\nfrom celery.schedules import crontab\nfrom decouple import config"
    )

    # 2. Update SECRET_KEY, DEBUG, ALLOWED_HOSTS
    content = re.sub(r"SECRET_KEY = .*", "SECRET_KEY = config('SECRET_KEY')", content)
    content = re.sub(r"DEBUG = .*", "DEBUG = config('DEBUG', default=False, cast=bool)", content)
    content = re.sub(
        r"ALLOWED_HOSTS = .*", 
        "ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost', cast=lambda v: [s.strip() for s in v.split(',')])", 
        content
    )

    # 3. Update INSTALLED_APPS
    apps_addition = """    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'channels',
    'drf_spectacular',"""
    content = re.sub(
        r"['\"]django\.contrib\.staticfiles['\"],",
        f"'daphne',\n    'django.contrib.staticfiles',\n{apps_addition}",
        content
    )

    # 4. Update MIDDLEWARE
    content = content.replace(
        "MIDDLEWARE = [",
        "MIDDLEWARE = [\n    'corsheaders.middleware.CorsMiddleware',\n    'whitenoise.middleware.WhiteNoiseMiddleware',"
    )

    # 5. Update DATABASES
    db_config = """DATABASES = {
    'default': {
        'ENGINE': config("DB_ENGINE", default="django.db.backends.sqlite3"),
        'NAME': config('DB_NAME', default=BASE_DIR / 'db.sqlite3'),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default=5432, cast=int),
        'CONN_MAX_AGE': config('CONN_MAX_AGE', default=600, cast=int),
    }
}"""
    content = re.sub(r"DATABASES\s*=\s*\{.*?\}\s*\}", db_config, content, flags=re.DOTALL)

    # 6. Update WSGI / ASGI
    content = re.sub(
        r"WSGI_APPLICATION\s*=\s*['\"]" + re.escape(name) + r"\.wsgi\.application['\"]",
        f"WSGI_APPLICATION = '{name}.wsgi.application'\nASGI_APPLICATION = '{name}.asgi.application'",
        content
    )

    # 6.5 Update Static / Media Files
    static_media_config = """STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'assets'
MEDIA_ROOT = BASE_DIR / 'media'"""
    content = re.sub(r"STATIC_URL\s*=\s*['\"]static/['\"]", static_media_config, content)

    # 7. Append custom configurations at the end
    custom_configs = """

# ── Caching Configuration (Redis) ─────────────────────────────────────────────
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": config("REDIS_URL", default="redis://127.0.0.1:6379/1"),
    }
}

# ── Security & Performance Settings ───────────────────────────────────────────
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ── Channels Configuration ────────────────────────────────────────────────────
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(config("REDIS_HOST", default="127.0.0.1"), config("REDIS_PORT", default=6379, cast=int))],
        },
    },
}

# ── REST Framework & JWT Settings ─────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'core.utils.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day'
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'API Documentation',
    'DESCRIPTION': 'Project API Documentation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ── CORS & CSRF Settings ──────────────────────────────────────────────────────
CSRF_TRUSTED_ORIGINS = [i.strip() for i in config("CSRF_TRUSTED_ORIGINS", "").split(",") if i]
CORS_ALLOWED_ORIGINS = [i.strip() for i in config("CORS_ALLOWED_ORIGINS", "").split(",") if i]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ['accept', 'accept-encoding', 'authorization', 'content-type', 'dnt', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with']
CORS_ALLOW_METHODS = ['DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT']

# ── Email Settings ────────────────────────────────────────────────────────────
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=True, cast=bool)
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_PORT = config('EMAIL_PORT', default=465, cast=int)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')

# ── Logging Configuration ─────────────────────────────────────────────────────
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "celery": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}

# ── Celery & Background Tasks ─────────────────────────────────────────────────
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="redis://127.0.0.1:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_TIME_LIMIT = 5 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 60
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Celery Beat Schedule
CELERY_BEAT_SCHEDULE = {
    "sample_task": {
        "task": "core.tasks.sample_task",
        "schedule": crontab(minute="*/15"),
    },
}
"""
    custom_configs = custom_configs.replace("core.utils.", f"{name}.utils.")
    custom_configs = custom_configs.replace("core.tasks.", f"{name}.tasks.")
    content += custom_configs

    with open(settings_path, "w", encoding="utf-8") as f:
        f.write(content)

    return secret_key


def create_directories():
    os.makedirs("apps", exist_ok=True)
    os.makedirs("static", exist_ok=True)
    os.makedirs("media", exist_ok=True)


def install_dependencies():
    packages = [
        "djangorestframework",
        "djangorestframework-simplejwt",
        "django-cors-headers",
        "python-decouple",
        "psycopg2-binary",
        "Pillow",
        "celery",
        "redis",
        "daphne",
        "channels",
        "channels-redis",
        "whitenoise",
        "drf-spectacular",
        "pytest",
        "pytest-django",
        "pytest-cov",
        "black",
        "flake8",
        "isort",
    ]
    total = len(packages)
    print("[cyan]📦 Installing dependencies...[/cyan]")
    for i, package in enumerate(packages, 1):
        print(f"[cyan]   [{i}/{total}] {package}[/cyan]")
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", package, "-q"],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            print(f"[red]Error installing {package}:\n{result.stderr}[/red]")
            import typer
            raise typer.Exit(1)
    print("[green]✔ All dependencies installed.[/green]")


def generate_env_file(secret_key: str, name: str):
    env_content = f"""# -----------------------------
# Django Secret Key & Debug
# -----------------------------
DEBUG=True
SECRET_KEY={secret_key}

# ALLOWED HOSTS
ALLOWED_HOSTS=localhost,127.0.0.1

# CORS SETTINGS------------------------------#
# CSRF trusted origins
CSRF_TRUSTED_ORIGINS=http://localhost:5173,http://127.0.0.1:8000

# CORS allowed origins
CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:8000


# -----------------------------
# Database: #'django.db.backends.postgresql',  # or 'django.db.backends.mysql', # or 'django.db.backends.sqlite3'
# -----------------------------
# DB_ENGINE=django.db.backends.postgresql
# DB_NAME={name}_db
# DB_USER={name}_user
# DB_PASSWORD=your-db-password
# DB_HOST=localhost
# DB_PORT=5432
# CONN_MAX_AGE=600

# -----------------------------
# Redis Configuration
# -----------------------------
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_URL=redis://localhost:6379/1
CELERY_BROKER_URL=redis://localhost:6379/0
CELERY_RESULT_BACKEND=redis://localhost:6379/0

# -----------------------------
# Email / SMTP Settings
# -----------------------------
EMAIL_USE_SSL=True
EMAIL_HOST=smtp.gmail.com
EMAIL_HOST_USER=your-email@gmail.com
EMAIL_HOST_PASSWORD=your-app-password
EMAIL_PORT=465
EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
"""
    with open(".env", "w", encoding="utf-8") as f:
        f.write(env_content)


def generate_docker_files(name: str):
    dockerfile_content = """FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update \\
    && apt-get install -y --no-install-recommends gcc libpq-dev \\
    && apt-get clean \\
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /app/
"""
    with open("Dockerfile", "w", encoding="utf-8") as f:
        f.write(dockerfile_content)

    docker_compose_content = f"""version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB={name}_db
      - POSTGRES_USER={name}_user
      - POSTGRES_PASSWORD={name}@1234!
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 {name}.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A {name} worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
"""
    with open("docker-compose.yml", "w", encoding="utf-8") as f:
        f.write(docker_compose_content)

    dockerignore_content = """.env
.venv
venv/
__pycache__/
*.pyc
db.sqlite3
media/
static/
"""
    with open(".dockerignore", "w", encoding="utf-8") as f:
        f.write(dockerignore_content)


def freeze_requirements():
    print("[cyan]📄 Freezing requirements...[/cyan]")
    result = subprocess.run(
        [sys.executable, "-m", "pip", "freeze", "--local"],
        capture_output=True, text=True
    )
    with open("requirements.txt", "w", encoding="utf-8") as f:
        f.write(result.stdout)
    print("[green]✔ requirements.txt created.[/green]")


def create_utils_file(name: str):
    utils_content = """from rest_framework.views import exception_handler

# Custom Message
def custom_exception_handler(exc, context):
    \"\"\"
    Global DRF exception handler.
    Always return only first error message.
    \"\"\"

    response = exception_handler(exc, context)

    if response is None:
        return response

    data = response.data

    # Case 1: {"detail": "..."}
    if isinstance(data, dict) and "detail" in data:
        message = data["detail"]

    # Case 2: serializer errors {"field": ["error"]}
    elif isinstance(data, dict):
        first_error = list(data.values())[0]

        if isinstance(first_error, list):
            message = first_error[0]
        else:
            message = first_error

    # Case 3: ["error"]
    elif isinstance(data, list):
        message = data[0]

    else:
        message = "Something went wrong."

    # Clean up technical messages
    message = str(message)
    if "JSON parse error" in message:
        message = "Invalid JSON format in request body."

    # Standardize response to include success: false
    response.data = {
        "success": False,
        "message": message
    }

    return response
"""
    with open(f"{name}/utils.py", "w", encoding="utf-8") as f:
        f.write(utils_content)


def create_celery_file(name: str):
    celery_content = f"""import os
from celery import Celery

# Set the default Django settings module for the 'celery' program.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', '{name}.settings')

app = Celery('{name}')

# Using a string here means the worker doesn't have to serialize
# the configuration object to child processes.
# - namespace='CELERY' means all celery-related configuration keys
#   should have a `CELERY_` prefix.
app.config_from_object('django.conf:settings', namespace='CELERY')

# Load task modules from all registered Django apps.
app.autodiscover_tasks()

@app.task(bind=True, ignore_result=True)
def debug_task(self):
    print(f'Request: {{self.request!r}}')
"""
    with open(f"{name}/celery.py", "w", encoding="utf-8") as f:
        f.write(celery_content)


def update_init_file(name: str):
    init_content = """from .celery import app as celery_app

__all__ = ('celery_app',)
"""
    with open(f"{name}/__init__.py", "w", encoding="utf-8") as f:
        f.write(init_content)


def update_urls_file(name: str):
    urls_content = """from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.http import JsonResponse
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


# ── Root / Health-check endpoint ──────────────────────────────────────────────
def root_view(request):
    return JsonResponse({
        "message": "API Server Running",
        "status": "ok"
    })


# ── URL Patterns ──────────────────────────────────────────────────────────────
urlpatterns = [
    # Root / Health-check
    path('', root_view, name='home'),

    # Django Admin Panel
    # Optional: Change 'admin/' to 'em-secure-admin/' in production for security
    path('admin/', admin.site.urls),

    # API Documentation
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""
    with open(f"{name}/urls.py", "w", encoding="utf-8") as f:
        f.write(urls_content)


def generate_gitignore():
    gitignore_content = """# ===========================
# Python / Django / Virtual Env
# ===========================
__pycache__/
*.py[cod]
*$py.class
*.so

env/
venv/
ENV/
.venv/
pyvenv.cfg

*.log
*.pot
*.pyc
*.pyo
*.pyd

# ===========================
# Database (PostgreSQL / MySQL)
# ===========================
*.dump
*.sql
*.backup
backups/
dumps/
db.sqlite3
db.sqlite3-journal
*.sqlite3
*.db

# ===========================
# Django migrations (optional)
# ===========================
# Ignore migrations if you handle them via CI/CD
# */migrations/*.py
# */migrations/*.pyc
# !*/migrations/__init__.py

# ===========================
# Static files / Media
# ===========================
/static/
/staticfiles/
/media/
/mediafiles/
/assets/

# ===========================
# Secrets / Environment variables
# ===========================
.env
.env.*
secret_key.txt
.secret_key
*.key
*.pem
*.crt
*.cer
credentials.json
secrets.json

# ===========================
# Caches / Temp
# ===========================
.cache/
.pytest_cache/
.mypy_cache/
django_cache/
tmp/
temp/

# ===========================
# Celery
# ===========================
celerybeat-schedule*
celerybeat-schedule
celerybeat-schedule-shm
celerybeat-schedule-wal
*.pid

# ===========================
# IDEs / Editors
# ===========================
.vscode/
.idea/
*.iml
*.sublime-project
*.sublime-workspace
*.swp
*~

# ===========================
# OS / System
# ===========================
.DS_Store
Thumbs.db
*.bak
*.orig
*.rej

# ===========================
# Docker
# ===========================
.docker/
docker-compose.override.yml

# ===========================
# Node / Frontend
# ===========================
node_modules/
dist/
build/
*.map

# ===========================
# Testing / Coverage
# ===========================
.coverage
htmlcov/
.tox/
.nox/
"""
    with open(".gitignore", "w", encoding="utf-8") as f:
        f.write(gitignore_content)


def generate_pytest_ini(name: str):
    content = f"""[pytest]
DJANGO_SETTINGS_MODULE = {name}.settings
python_files = tests.py test_*.py *_tests.py
addopts = --cov=. --cov-report=html
"""
    with open("pytest.ini", "w", encoding="utf-8") as f:
        f.write(content)


def generate_pre_commit_config():
    content = """repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
"""
    with open(".pre-commit-config.yaml", "w", encoding="utf-8") as f:
        f.write(content)


def generate_github_actions():
    os.makedirs(".github/workflows", exist_ok=True)
    content = """name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run Tests
      run: |
        pytest
"""
    with open(".github/workflows/main.yml", "w", encoding="utf-8") as f:
        f.write(content)


def generate_gitlab_ci():
    content = """image: python:3.11-slim

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

test_project:
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - pytest
"""
    with open(".gitlab-ci.yml", "w", encoding="utf-8") as f:
        f.write(content)


def create_project(name: str):
    check_virtual_environment()
    validate_name(name, "project name")

    # Check if project already exists
    if Path(name).exists():
        print(f"[red]Error: A directory named '{name}' already exists. Choose a different name or delete it first.[/red]")
        import typer
        raise typer.Exit(1)

    # Check if current directory already has a manage.py (already a Django project)
    if Path("manage.py").exists():
        print("[red]Error: manage.py already exists here. Are you already inside a Django project?[/red]")
        import typer
        raise typer.Exit(1)

    print(f"[green]🚀 Creating Django project: {name}[/green]")

    # Install Django first so django-admin is available
    print("[cyan]📦 Installing Django first...[/cyan]")
    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", "Django"],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"[red]Failed to install Django:\n{result.stderr}[/red]")
        import typer
        raise typer.Exit(1)

    result = subprocess.run(
        [sys.executable, "-m", "django", "startproject", name, "."],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"[red]Failed to create Django project:\n{result.stderr}[/red]")
        import typer
        raise typer.Exit(1)

    secret_key = update_settings_file(f"{name}/settings.py", name)
    create_utils_file(name)
    create_celery_file(name)
    update_init_file(name)
    update_urls_file(name)
    create_directories()
    install_dependencies()
    generate_env_file(secret_key, name)
    freeze_requirements()
    generate_docker_files(name)
    generate_gitignore()
    generate_pytest_ini(name)
    generate_pre_commit_config()

    print()
    print(f"[bold green]✅ Project '{name}' created successfully![/bold green]")
    print()
    print("[cyan]Next steps:[/cyan]")
    print(f"  1. Update your [bold].env[/bold] file with DB credentials")
    print(f"  2. Run [bold]git init[/bold]")
    print(f"  3. Run [bold]python manage.py migrate[/bold]")
    print(f"  4. Run [bold]python manage.py runserver[/bold]")